version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels: [dependencies, javascript]
    groups:
      javascript-minor-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, python]
    groups:
      python-minor-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, github-actions]
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, docker]
    groups:
      docker-minor-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, docker]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, docker]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
